from pathlib import Path

"""
Build a report for a training job.

TODO
========
* Overall fraction true vs false
* true vs false per job / as a function of particle number
* Fraction of K and T
* full ROC data
* Plot of loss and accuracy over epochs

"""


def generate_evaluation(
    data,
    input_path: Path,
    output_path: Path,
    overwrite: bool,
) -> None:
    """
    Generate a report that evaluates a training dataset
    """
    # Create the report directory
    output_path = Path(output_path)
    output_dir = output_path.parent / (output_path.stem + "_results")
    output_dir.mkdir(parents=True, exist_ok=True)

    return output_dir


def generate_report():
    """
    Generates a report of a training run.

    TODO
    ======
    * parse directory of models
    * append figures to previous report generated by generate_evaluation
    """
